In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
#daten aus csv einlesen
df = pd.read_csv('Big5.csv')
df.head()

,1_Player,2_Nation,3_Pos,4_Squad,5_Comp,6_Age,7_Born,Playing Time_MP,Playing Time_Starts,Playing Time_Min,...,Expected_xG,Expected_npxG,Expected_xA,Expected_npxG+xA,Per 90 Minutes_xG,Per 90 Minutes_xA,Per 90 Minutes_xG+xA,Per 90 Minutes_npxG,Per 90 Minutes_npxG+xA,33_Matches
0,Max Aarons,eng ENG,DF,Norwich City,eng Premier League,22-070,2000,28,27,2398,...,0.7,0.7,1.0,1.6,0.02,0.04,0.06,0.02,0.06,Matches
1,Yunis Abdelhamid,ma MAR,DF,Reims,fr Ligue 1,34-168,1987,25,25,2173,...,1.0,1.0,0.2,1.2,0.04,0.01,0.05,0.04,0.05,Matches
2,Salis Abdul Samed,gh GHA,MF,Clermont Foot,fr Ligue 1,21-354,2000,25,24,2057,...,0.7,0.7,0.9,1.6,0.03,0.04,0.07,0.03,0.07,Matches
3,Laurent Abergel,fr FRA,MF,Lorient,fr Ligue 1,29-042,1993,24,24,2089,...,1.8,1.8,2.1,3.8,0.08,0.09,0.17,0.08,0.17,Matches
4,Charles Abi,fr FRA,FW,Saint-Étienne,fr Ligue 1,21-337,2000,1,1,45,...,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,Matches

In [7]:
#Daten enthalten "header"-daten welche immer mit "player beginnen" -> bereinigen
players = df['1_Player']
df = df[players != 'Player']
players.duplicated(keep='first').sum()

245

In [10]:
#Goals und Assists in Integer umwandeln
df['Performance_Gls'] = df['Performance_Gls'].astype('int64')
df['Performance_Ast'] = df['Performance_Ast'].astype('int64')
df.dtypes

1_Player                  object
2_Nation                  object
3_Pos                     object
4_Squad                   object
5_Comp                    object
6_Age                     object
7_Born                    object
Playing Time_MP           object
Playing Time_Starts       object
Playing Time_Min          object
Playing Time_90s          object
Performance_Gls            int64
Performance_Ast            int64
Performance_G-PK          object
Performance_PK            object
Performance_PKatt         object
Performance_CrdY          object
Performance_CrdR          object
Per 90 Minutes_Gls        object
Per 90 Minutes_Ast        object
Per 90 Minutes_G+A        object
Per 90 Minutes_G-PK       object
Per 90 Minutes_G+A-PK     object
Expected_xG               object
Expected_npxG             object
Expected_xA               object
Expected_npxG+xA          object
Per 90 Minutes_xG         object
Per 90 Minutes_xA         object
Per 90 Minutes_xG+xA      object
Per 90 Minutes_npxG       object
Per 90 Minutes_npxG+xA    object
33_Matches                object
dtype: object

In [11]:
# Erkentniss: Es gibt Dublikate weil gewisse Spieler bei meherern Teams gespielt haben 
# -> Assists und Goals summieren und dublikate "droppen"

df['Performance_Gls'] = df.groupby('1_Player')['Performance_Gls'].transform('sum')
df['Performance_Ast'] = df.groupby('1_Player')['Performance_Ast'].transform('sum')
df = df.drop_duplicates(subset='1_Player')

In [12]:
df.shape

(2664, 33)

In [15]:
#Nur die "spannenden" Spalten behalten
df1 = df[['1_Player','4_Squad', '6_Age', 'Performance_Gls', 'Performance_Ast']]
df1.head()

            1_Player        4_Squad   6_Age  Performance_Gls  Performance_Ast
0         Max Aarons   Norwich City  22-070                1                1
1   Yunis Abdelhamid          Reims  34-168                0                0
2  Salis Abdul Samed  Clermont Foot  21-354                0                0
3    Laurent Abergel        Lorient  29-042                2                2
4        Charles Abi  Saint-Étienne  21-337                0                0